### ISSUE TITLE
Running the app on Gnome Shell (41) has theming issues

### ISSUE THREAD

**Issue by ToxicDragon** [SubhadeepJasu/Ensembles#21] opened 2021-09-02 17:08 UTC
Hi there,

congratulations to the wonderful application!

I just installed the app via flatpak on Gnome 41 (Ubuntu) and started it. However, the theming seems to be using the gnome themes and looks kind of broken aswell (see screenshot).

![image](https://user-images.githubusercontent.com/3375142/131887323-c85a1582-50d9-4b12-9c9c-eca69ef7977b.png)

Additionally, here is the log output when running the app from command line:
```flatpak run com.github.subhadeepjasu.ensembles

Gtk-Message: 19:01:10.874: Failed to load module "appmenu-gtk-module"
fluidsynth: Using PulseAudio driver
fluidsynth: Using PulseAudio driver
fluidsynth: warning: Failed to set thread to high priority
fluidsynth: Using PulseAudio driver
fluidsynth: warning: Failed to set thread to high priority
Ticks: ///////// 480 //////
Time Signature = 3/4
Style: /// Config:1;90,0 0
Style: /// IntroA:2 1440
Style: /// IntroB:4 4320
Style: /// VarA:12 15840
Style: /// FillA:14 18720
Style: /// VarB:15 20160
Style: /// FillB:17 23040
Style: /// VarC:18 24480
Style: /// FillC:20 27360
Style: /// VarD:21 28800
Style: /// FillD:23 31680
Style: /// EndingA:24 33120
Style: /// EOS1:28 38880
Style: /// EndingB:29 40320
Style: /// EOS2:34 47520
Ticks: ///////// 480 //////
Time Signature = 4/4
Style: /// Config:1;125,1 0
Style: /// IntroA:2 1920
Style: /// IntroB:4 5760
Style: /// VarA:12 21120
Style: /// FillA:14 24960
Style: /// VarB:15 26880
Style: /// FillB:17 30720
Style: /// VarC:18 32640
Style: /// FillC:20 36480
Style: /// VarD:21 38400
Style: /// FillD:23 42240
Style: /// EndingA:24 44160
Style: /// EOS:26 48000
Style: /// EndingB:32 59520
Style: /// EOS:40 74880
Ticks: ///////// 480 //////
Time Signature = 4/4
Style: /// Config:1;100,1 0
Style: /// IntroA:2 1920
Style: /// IntroB:4 5760
Style: /// VarA:12 21120
Style: /// FillA:14 24960
Style: /// VarB:15 26880
Style: /// FillB:17 30720
Style: /// VarC:18 32640
Style: /// FillC:20 36480
Style: /// VarD:21 38400
Style: /// FillD:23 42240
Style: /// EndingA:24 44160
Style: /// EOS:26 48000
Style: /// EndingB:32 59520
Style: /// EOS:41 76800
Ticks: ///////// 480 //////
Time Signature = 4/4
Style: /// Config:1;125,1 0
Style: /// IntroA:2 1920
Style: /// IntroB:4 5760
Style: /// VarA:12 21120
Style: /// FillA:14 24960
Style: /// VarB:15 26880
Style: /// FillB:17 30720
Style: /// VarC:18 32640
Style: /// FillC:20 36480
Style: /// VarD:21 38400
Style: /// FillD:23 42240
Style: /// EndingA:24 44160
Style: /// EOS:28 51840
Style: /// EndingB:32 59520
Style: /// EOS:40 74880
Ticks: ///////// 480 //////
Time Signature = 4/8
Style: /// Config:1;80,1 0
Style: /// Intro1:2 960
Style: /// Intro2:6 4800
Style: /// VarA:22 20160
Style: /// FillA:26 24000
Style: /// VarB:28 25920
Style: /// FillB:32 29760
Style: /// VarC:34 31680
Style: /// FillC:38 35520
Style: /// VarD:40 37440
Style: /// FillD:44 41280
Style: /// Ending1:46 43200
Style: /// EOS:50 47040
Style: /// Ending2:55 51840
Style: /// EOS:60 56640
Ticks: ///////// 480 //////
Time Signature = 4/4
Style: /// Config:1;110,1 0
Style: /// IntroA:2 1920
Style: /// IntroB:4 5760
Style: /// VarA:12 21120
Style: /// FillA:14 24960
Style: /// VarB:15 26880
Style: /// FillB:17 30720
Style: /// VarC:18 32640
Style: /// FillC:20 36480
Style: /// VarD:21 38400
Style: /// FillD:23 42240
Style: /// EndingA:24 44160
Style: /// EOS:28 51840
Style: /// EndingB:32 59520
Style: /// EOS:40 74880
fluidsynth: warning: Failed to set thread to high priority
ts: 4
fluidsynth: Using PulseAudio driver
fluidsynth: warning: Failed to set thread to high priority

** (com.github.subhadeepjasu.ensembles:2): WARNING **: 19:01:11.538: MediaKeyListener.vala:61: Could not grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
chan...to /app/share/com.github.subhadeepjasu.ensembles/StyleFiles/Ball_Room@French_Waltz.enstl
Ticks: ///////// 480 //////
Time Signature = 3/4
Style: /// Config:1;90,0 0
Style: /// IntroA:2 1440
Style: /// IntroB:4 4320
Style: /// VarA:12 15840
Style: /// FillA:14 18720
Style: /// VarB:15 20160
Style: /// FillB:17 23040
Style: /// VarC:18 24480
Style: /// FillC:20 27360
Style: /// VarD:21 28800
Style: /// FillD:23 31680
Style: /// EndingA:24 33120
Style: /// EOS1:28 38880
Style: /// EndingB:29 40320
Style: /// EOS2:34 47520
changing...to /app/share/com.github.subhadeepjasu.ensembles/StyleFiles/Ball_Room@French_Waltz.enstl
e:
f:
90 >>>>
g:
h
ts: 4```

**Comment by SubhadeepJasu** [comment] 2021-09-02 17:33
Its a known issue, I plan to fix it the same way Akira does by forcing the app the use elementary theme.

**Comment by SubhadeepJasu** [comment] 2021-09-02 18:59
#22

**Comment by SubhadeepJasu** [comment] 2021-09-03 07:33
[Enigma.zip](https://github.com/SubhadeepJasu/Ensembles/files/7104058/Enigma.zip) 

From my testing, it seems the issue is fixed. @ToxicDragon  , can you install this bundle and confirm that its working for you too?

**Comment by SubhadeepJasu** [comment] 2021-09-03 07:38
The issue seems to have been fixed when I tested it. @ToxicDragon Can you please test this bundle and confirm that its okay on your end too? 

https://api.github.com/repos/SubhadeepJasu/Ensembles/actions/artifacts/89219391/zip

**Comment by SubhadeepJasu** [comment] 2021-09-03 07:39
Damn looks like github isn't allowing me to upload the flatpak bundle

**Comment by SubhadeepJasu** [comment] 2021-09-03 07:42
Let me know if you are not able to access the artifacts from this pull request https://github.com/SubhadeepJasu/Ensembles/pull/22/checks . In that case I'll make another release.

**Comment by ToxicDragon** [comment] 2021-09-03 08:16
@SubhadeepJasu Would it be possible for you to provide "Main"/"Alpha" Build versions directly via the appcenter flatpakrepo? Because I installed the app via the existing flatpakrepo and it would be convenient to have an "apha" source for this aswell.

If not possible, I'll try to test your provided bundle.

**Comment by SubhadeepJasu** [comment] 2021-09-03 08:27
Not without releasing it. The alpha is released on the main branch.

**Comment by SubhadeepJasu** [comment] 2021-09-03 08:49
Ok, I'm gonna release this in appcenter. Hopefully the issue is fixed. Fingers crossed.

**Comment by SubhadeepJasu** [comment] 2021-09-03 09:27
https://github.com/SubhadeepJasu/Ensembles/releases/tag/v0.0.13 Has the latest fixes. It will be while before this appears on appcenter.

**Comment by ToxicDragon** [comment] 2021-09-03 10:19
> https://github.com/SubhadeepJasu/Ensembles/releases/tag/v0.0.13 Has the latest fixes. It will be while before this appears on appcenter.

I can confirm that this version respects the theming (apparently?) correctly (see the picture below). However, when switching to the system's light theme, the application does a) not switch to the light theme on the fly (Gnome System Apps do) and b) does not switch to light theme at all, even after restarting the app. But maybe a) is expected behaviour for flatpak apps and/or b) is also dependent on the themes available to flatpak OR the application's code only supports dark mode? What do you think @SubhadeepJasu ?

Additionally, it is now possible to resize the window. This was at least not possible horizontally in the previous build. Therefore, the keys of the keyboard do not look too wide anymore.

![image](https://user-images.githubusercontent.com/3375142/131989416-47c10d84-6f22-4d92-ad5d-6c158f494a9b.png)

**Comment by ToxicDragon** [comment] 2021-09-03 10:21
Update: On second thought, the application's theme resembles - as noted by @SubhadeepJasu - elementary's theme. However it is interesting that only the dark theme is used, not the light one.

**Comment by SubhadeepJasu** [comment] 2021-09-03 10:23
Its only designed around a dark theme. That's just how it is. The stylesheet doesn't support any light background colors.

**Comment by ToxicDragon** [comment] 2021-09-03 10:41
Alright, then most visual parts seem to be fine! I mean there some quirks here and there, see the comparison (e.g. the control in the top left corner are truncated a bit).

Original image (elementry OS):
![image](https://user-images.githubusercontent.com/3375142/131992850-59590c04-6c96-47bf-b20e-885eb3b39fbd.png)

0.0.13 on Gnome Shell (41):
![image](https://user-images.githubusercontent.com/3375142/131992947-4738ed3d-84c3-4516-9fcf-d6144daae054.png)

**Comment by ToxicDragon** [comment] 2021-09-03 10:42
But in general it looks quite good now!

**Comment by SubhadeepJasu** [comment] 2021-09-03 10:45
Yeah those visual issues are what I was talking about. Okay, we can close this issue, I'll make a new issue to track the visual quirks.

**Comment by SubhadeepJasu** [comment] 2021-09-03 10:46
Thanks for bringing this up!

**Closed by SubhadeepJasu** 2021-09-03 10:46 UTC
Labels: Priority: Medium, Status: Confirmed, Flatpak

**Comment by ToxicDragon** [comment] 2021-09-03 16:22
Sounds good! Thank you for your quick responses and bug fixing; I'm overwhelmed! Really nice application!

**Comment by j-james** [comment] 2022-02-17 10:29
Hmm, I'm running into this issue! On Arch Linux, with gnome-shell 41.3 and the arc-gtk-theme installed:

![2022-02-17-022157](https://user-images.githubusercontent.com/35242550/154456157-204d6d23-093c-464c-8d19-d4128fa8ddc4.png)

@SubhadeepJasu: Maybe I missed a dependency in my AUR package: does [this list](https://aur.archlinux.org/packages/ensembles) look right to you?

**Comment by SubhadeepJasu** [comment] 2022-02-17 10:35
Hey! Thanks for putting it in aur. In the list I would suggest also having elementary style sheet. Without that the app isn't gonna render correctly.

**Comment by j-james** [comment] 2022-02-17 11:05
Alright, I think gtk-theme-elementary provides the elementary style sheet on Arch. It renders in dark mode now but still doesn't use the system theme. `granite-demo` appears to work fine, so is that on this end or am I missing something else?

![2022-02-17-025621](https://user-images.githubusercontent.com/35242550/154466310-da386b41-384a-446c-b6e3-270d40a38c11.png)

I've added as optional dependencies `gtk-theme-elementary`, `portmidi` (previously required), `lv2`, `lilv` (`serd`, `sord`, and `sratom` are dependencies), and `suil`, which I think should be all the lv2 packages. What does Ensembles use `suil` for? I put in brief descriptions for the rest, but couldn't quite figure that one out.

**Comment by SubhadeepJasu** [comment] 2022-02-20 04:22
That's okay. Ensembles is designed to use only the elementary theme and then add modifications on top of that. It won't use system them by design, plus it will only use dark theme, that's by design. It's a dark theme app. 

It uses suil for rendering gtk ui for lv2 plugins, well that's what its supposed to do, but someone just told me that suil doens't yet support gtk 3 or gtk 4 yet, so that feature is dead in the water.
